# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Deltastring
tagline:          'Zendesk implementation specialists'
description:      'Is your Zendesk AI-ready?'
url:              https://deltastring.com
baseurl:          /

author:
  name:           'Nico Boyce'
  url:            https://deltastring.com

# paginate:         4

# plugins:
#  - jekyll-paginate-v2
#  - jekyll-gist

# Custom vars
version:          âˆš2

excerpt_separator: "<!--excerpt-end-->"
# github:
#   repo:           https://github.com/poole/hyde
